java_library(
	name = "CatfoodCore",
	srcs = glob(["src/main/java/**/*.java"]),
	deps = ["@maven//:org_projectlombok_lombok","@maven//:io_vertx_vertx_core","@maven//:com_fasterxml_jackson_core_jackson_annotations"],
	visibility = ["//visibility:public"]
)
